/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __STM32F1__H
#define __STM32F1__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_STM32F1(Args *args);

Arg* STM32F1_ADC(PikaObj *self);
Arg* STM32F1_GPIO(PikaObj *self);
Arg* STM32F1_IIC(PikaObj *self);
Arg* STM32F1_PWM(PikaObj *self);
Arg* STM32F1_Time(PikaObj *self);
Arg* STM32F1_UART(PikaObj *self);
Arg* STM32F1_lowLevel(PikaObj *self);

#endif
